### PR TITLE
Fix kibana 4.4.0

### PR DESCRIPTION
**Pull request by johnjelinek**
Running this role on CentOS wasn't working for me. After these changes, it works :)

### CODE REVIEW

**Comment by johnjelinek** [comment]
`NODE_ENV` might not even be necessary anymore.

**Comment by johnjelinek** [comment]
@mrlesmithjr: in my case, when `babelcache` is found to exist, it doesn't have the right permissions. Is it bad form to always set it to `o+w`?

**Comment by johnjelinek** [comment]
@mrlesmithjr: I incorporated your suggestions.

**Comment by mrlesmithjr** [comment]
@johnjelinek - Not bad form for the o+w....But the state: touch will always report as changed so if you just  set the perms and leave state out of the task then you should be good.

Did you validate that it works after changing :)

**Comment by johnjelinek** [comment]
ya, as it stands right now, I've confirmed that everything works (for me). It might be good to plug this playbook into travis CI for confirmation :)

**Comment by mrlesmithjr** [comment]
Changes have been merged...thanks!

**Pull request merged**
